version: '3.8'

services:
  web:
    build: .
    image: gestion_absences_image:latest
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypass
      POSTGRES_DB: gestion_absences_db
    volumes:
      - dbdata:/var/lib/postgresql/data

volumes:
  dbdata:
