apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins
  namespace: jenkins

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jenkins-role
  namespace: jenkins
rules:
- apiGroups: [""]
  resources: ["pods", "services", "endpoints", "namespaces", "nodes", "configmaps", "secrets", "replicasets", "deployments", "pods/exec", "pods/log"]  # Liste de ressources nécessaires pour Jenkins
  verbs: ["list", "get", "create", "delete", "update"]

- apiGroups: ["apps"]
  resources: ["deployments", "replicasets", "statefulsets"]
  verbs: ["list", "get", "create", "delete", "update"]

- apiGroups: ["batch"]
  resources: ["jobs", "cronjobs"]
  verbs: ["list", "get", "create", "delete", "update"]

- apiGroups: ["extensions"]
  resources: ["ingresses"]
  verbs: ["list", "get", "create", "delete", "update"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-role-binding
  namespace: jenkins
subjects:
- kind: ServiceAccount
  name: jenkins
  namespace: jenkins
roleRef:
  kind: Role
  name: jenkins-role
  apiGroup: rbac.authorization.k8s.io